Better error handling when module is not found
I have added a type check for message so that when moonboots-static can not find a module it will indicate as such and throw an appropriate error instead of throwing an "TypeError: undefined is not a function"